apiVersion: v1
kind: Service
metadata:
  name: dns-svc-tcp-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: somekey 
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
  loadBalancerIP: 172.17.255.10
#web-svc-cip 10.96.172.21