---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: canary
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: canary
  labels:
    app: web
spec:
  selector:
    app: web
    version: v1.0.0
  #type: ClusterIP
  #clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
#web-svc-cip 10.96.172.21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-svc
  namespace: canary
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      version: v1.0.0
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: web
        version: v1.0.0
    spec:
      containers:
      - name: web
        image: atalabirchuk/otus:lab_1_v1
        env:
        - name: VERSION
          value: v1.0.0
        volumeMounts:
          - name: app
            mountPath: /app
        livenessProbe:
          tcpSocket:
            port: 8000
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
      initContainers:
      - name: init-myservice
        image: busybox:1.31.0
        command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
        volumeMounts:
        - name: app
          mountPath: /app
      volumes:
      - name: app
        emptyDir: {}            