---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: checkoutservice
  namespace: microservices-demo
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true" #Аннотация разрешает автоматическое обновление релиза в Kubernetes кластере в случае изменения версии Docker образа в Registry
    flux.weave.works/tag.chart-image: semver:~v0.0 #Указываем Flux следить за обновлениями конкретных Docker образов в Registry. Новыми считаются только образы, имеющие версию выше текущей и отвечающие маске семантического версионирования ~0.0 (например, 0.0.1, 0.0.72, но не 1.0.0)
spec:
  releaseName: checkoutservice
  helmVersion: v3
  chart: #Helm chart, используемый для развертывания релиза. В нашем случае указываем git-репозиторий, и директорию с чартом внутри него
    git: git@gitlab.com:talabirchuk.a/microservices-demo.git
    ref: master
    path: deploy/charts/checkoutservice
  values: #Переопределяем переменные Helm chart. В дальнейшем Flux может сам переписывать эти значения и делать commit в git- репозиторий (например, изменять тег Docker образа при его обновлении в Registry)
    image:
      repository: atalabirchuk/checkoutservice
      tag: v0.0.2
