---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jane # под этим именем мы потом увидим этот RoleBinding
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
  resourceNames: ["admin"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jane
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: jane