---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken # под этим именем мы потом увидим этот RoleBinding
  namespace: dev
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-view: "true"  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount # Group, ServiceAccount
  name: ken # имя чувствительно к регистру
  namespace: dev