apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: netperf-calico-policy
  labels:
spec:
  order: 10
  selector: app == "netperf-operator"
  ingress: 
    - action: Allow
      source:
        selector: netperf-type == "client"
#        selector: netperf-role == "netperf-server" 
    - action: Log
    - action: Deny
  egress:
    - action: Allow
      source:
        selector: netperf-type == "client"
    - action: Log
    - action: Deny