apiVersion: v1
kind: Service
metadata:
  name: minio-lb
  # labels:
  #   app: minio
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: minio
  loadBalancerIP: 172.17.255.6