---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carol # под этим именем мы потом увидим этот RoleBinding
  namespace: prometheus
  # labels:
  #   # Add these permissions to the "admin" and "edit" default roles.
  #   rbac.authorization.k8s.io/aggregate-to-admin: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount # Group, ServiceAccount
  name: carol # имя чувствительно к регистру
  namespace: prometheus
  apiGroup: rbac.authorization.k8s.io
#kubectl auth can-i list pods --as system:serviceaccount:prometheus:carol -n prometheus
#kubectl auth can-i list pods --as system:serviceaccount:prometheus:carol
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prometheus
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]