---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob # под этим именем мы потом увидим этот RoleBinding
  namespace: default
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount # Group, ServiceAccount
  name: bob # имя чувствительно к регистру
  namespace: default