apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-test
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nginx-test
  endpoints:
  - port: nginx-exporter