apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
    tier: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice  
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate      
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: atalabirchuk/otus:hipsterpaymentservice-v0.0.1