apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paymentservice
  labels:
    app: paymentservice
    tier: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice  
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: atalabirchuk/otus:hipsterpaymentservice-v0.0.1           