apiVersion: v1
kind: PersistentVolume
metadata: 
  name: storage-pvc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms: 
      - matchExpressions:
        - {key: environment, operator: NotIn, values: [dev]}