apiVersion: v1
kind: Pod
metadata:
  name:  storage-pod
  labels:
    name:  storage-pod
spec:
  containers:
  - name:  storage-pod
    image: busybox
    command: ["sh", "-ec", "sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    volumeMounts:
      - mountPath: /data
        name: test-pvc
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
          claimName:  storage-pvc
