alertmanager:
  alertmanagerSpec:
    nodeSelector:
      cloud.google.com/gke-nodepool: infra-pool
    tolerations: 
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
prometheusOperator:
  admissionWebhooks:
    patch:
      nodeSelector:
        cloud.google.com/gke-nodepool: infra-pool
      tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule      
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool
  tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule   
prometheus:
  prometheusSpec:
    retention: 3d  
    tolerations:
      cloud.google.com/gke-nodepool: infra-pool
    nodeSelector:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule    
  service:
    nodePort: 31060
grafana:
  adminPassword: admin