---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.service.type.type }}
  selector:
    app: frontend
  ports:
  - name: http
    port: {{ .Values.service.ports.port | default "80" }}
    targetPort: {{ .Values.service.ports.targetPort | default "8080" }}
    {{- if eq .Values.service.type.type "NodePort" }}    
    nodePort: {{ .Values.service.ports.nodePort | default "30675" }}
    {{- end }}